#' ArfimaMLM plotting function
#' 
#' Function for plotting time-varying coefficients generated by Arfima-MLM package
#' 
#' @param Model Object of class ArfimaMLM
#' @param CoefName Name of time varying coefficient you wish to plot.
#' @param TimeVar Variable specifying unit of time.
#' @param loess TRUE sets loess smoother on.  FALSE disables features.  Defaults to TRUE.
#' @param title Character string to pass on to ggtitle.
#' @param xaxis Character string to pass on to ggplot2.  Defaults to "Date" if left blank.  
#' @param yaxis Character string to pass on to ggplot2.  Defaults to coefficient name if left blank.
#' 
#' @author David L Stack, \email{stackd85@gmail.com}
#' 

ArfimaMLM.plot<- function(Model, CoefName, TimeVar, 
                          loess = NULL, title = NULL,
                          xaxis = NULL, yaxis = NULL) {
  # Extract coefficients from ArfimaMLM object
  Model1<- Model$result
  require(lme4)
  ran.coef<- coef(Model1)
  ran.coef2<- data.frame(ran.coef[[1]])
  rm(ran.coef)
  # Create dataframe of coefficients and dates to use in plot.
  slope<-  ran.coef2[,CoefName]
  Date<- as.character(row.names(ran.coef2))
  Date<- as.numeric(Date)
  plot.frame<- data.frame(Date, slope)
  # plot.frame<- ran.coef2 %>%
  #   select_(Date, Coefname)
  #plot coefficients
  require(ggplot2)
  ArfimaPlot<- ggplot(plot.frame, 
                      aes(x = Date, y = slope)) + 
    geom_line(aes())
  if (missing(title)) {
    ArfimaPlot<- ArfimaPlot
  } else ArfimaPlot<- ArfimaPlot + 
    ggtitle(title) +
    theme(plot.title = element_text(hjust = 0.5))
  if (missing(loess)){
    ArfimaPlot<- ArfimaPlot
  } else if (loess == TRUE) {
#    ArfimaPlot<- ArfimaPlot
    ArfimaPlot<- ArfimaPlot + geom_smooth(aes(),
                method = "loess")
  } else if (loess == FALSE) {
    ArfimaPlot<- ArfimaPlot
  }
  if (missing(xaxis)) {
    ArfimaPlot<- ArfimaPlot
  } else ArfimaPlot<- ArfimaPlot + 
      xlab(xaxis)
  if (missing(yaxis)) {
    ArfimaPlot <- ArfimaPlot
  } else ArfimaPlot <- ArfimaPlot +
    ylab(yaxis)
  
  return(ArfimaPlot)
}


####Replication of Figure 4 from ARFIMA-MLM paper

# library(ArfimaMLM)

#' @examples 
#' 
#' load("full.house.replication.Rdata")
#' Mod1<- arfimaMLM(majpu.ydif~ minpu.xdif + policyvote + longsession + session1 +
#'                    minpu.fd + majn1s.fd + majn2s.fd+medmedn1.fd +
#'                    medmedn2.fd + majsize.fd + (1 + minpu.xdif|year),
#'                  data=full.house, timevar="year")




#' testplot<- ArfimaMLM.plot(Mod1, "minpu.xdif", year, loess = TRUE,
#'                          title = "Varying Slope (Minority Party Unity)",
#'                          xaxis = "Date", 
#'                          yaxis = "Slope on Minority Party Unity")

#' print(testplot)
#' 
#' @export
#' 
